/**
 * @file PromptDisplay.tsx
 * @description This component displays the content of the selected system prompt
 * and the analysis generated by the AI.
 */

'use client';

import React, { useState, useEffect, useRef } from 'react';
import { marked } from 'marked'; // For rendering Markdown content
import DOMPurify from 'dompurify'; // For sanitizing HTML to prevent XSS attacks

/**
 * @interface PromptDisplayProps
 * @description Defines the props for the PromptDisplay component.
 */
interface PromptDisplayProps {
  /** The filename of the currently selected prompt. Null if none is selected. */
  selectedPrompt: string | null;
  /** Callback function to pass the fetched prompt content to the parent component. */
  onPromptContentLoaded: (content: string) => void;
  /** An array of AI analysis strings to be displayed. */
  aiAnalysis: string[];
}

/**
 * A component to display the selected prompt's content and AI analysis.
 * @param {PromptDisplayProps} props - The props for the component.
 * @returns {JSX.Element} The rendered component.
 */
const PromptDisplay: React.FC<PromptDisplayProps> = ({ selectedPrompt, onPromptContentLoaded, aiAnalysis }) => {
  const [content, setContent] = useState(''); // State for the selected prompt's content.
  const [copyButtonText, setCopyButtonText] = useState('Copy'); // State for the copy button text.
  const [analysisHtml, setAnalysisHtml] = useState(''); // State for the sanitized HTML of the AI analysis.
  const analysisEndRef = useRef<HTMLDivElement>(null); // Ref for auto-scrolling the analysis view.

  /**
   * @function scrollToBottom
   * @description Smoothly scrolls the analysis container to the bottom.
   */
  const scrollToBottom = () => {
    analysisEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  /**
   * @effect
   * @description Fetches the content of the selected prompt whenever it changes.
   */
  useEffect(() => {
    if (selectedPrompt) {
      const fetchPromptContent = async () => {
        try {
          const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/prompts/${selectedPrompt}`);
          const data = await response.json();
          setContent(data.content);
          onPromptContentLoaded(data.content);
        } catch (error) {
          console.error('Error fetching prompt content:', error);
          const errorContent = 'Error loading prompt.';
          setContent(errorContent);
          onPromptContentLoaded(errorContent);
        }
      };

      fetchPromptContent();
    } else {
      // Clear content if no prompt is selected
      setContent('');
      onPromptContentLoaded('');
    }
  }, [selectedPrompt, onPromptContentLoaded]);

  /**
   * @effect
   * @description Renders the AI analysis as sanitized HTML whenever the analysis array changes.
   */
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const fullAnalysis = aiAnalysis.length > 0
        ? aiAnalysis.map((analysis, index) => `<h3>Analysis #${index + 1}</h3>\n\n${analysis}`).join('<hr class="my-4"/>')
        : 'No analysis available. Start a chat to generate one.';

      const sanitizedHtml = DOMPurify.sanitize(marked.parse(fullAnalysis) as string);
      setAnalysisHtml(sanitizedHtml);
      scrollToBottom();
    }
  }, [aiAnalysis]);

  /**
   * @function handleCopy
   * @description Copies the full text of all AI analyses to the clipboard.
   */
  const handleCopy = () => {
    const fullAnalysisText = aiAnalysis.map((analysis, index) => `--- Analysis #${index + 1} ---\n\n${analysis}`).join('\n\n');
    navigator.clipboard.writeText(fullAnalysisText).then(() => {
      setCopyButtonText('Copied!');
      setTimeout(() => setCopyButtonText('Copy'), 2000);
    });
  };

  return (
    <div className="w-1/2 bg-white p-4 flex flex-col">
      <h2 className="text-lg font-bold mb-4 text-black">
        {selectedPrompt ? `Selected Prompt: ${selectedPrompt}` : 'Selected Prompt'}
      </h2>
      {/* Display area for the system prompt content */}
      <div className="w-full flex-grow p-4 bg-gray-100 rounded-lg overflow-y-auto">
        <p className="text-black whitespace-pre-wrap break-words">{content || 'Select a prompt from the list to see its content.'}</p>
      </div>

      {/* Collapsible section for AI analysis */}
      <div className="mt-4 border rounded-lg">
        <details className="p-4">
          <summary className="font-bold cursor-pointer text-black flex justify-between items-center">
            <span>AI Analysis</span>
            {aiAnalysis.length > 0 && (
              <button 
                className="bg-gray-200 text-black text-xs py-1 px-2 rounded-md hover:bg-gray-300"
                onClick={(e) => {
                  e.preventDefault(); // prevent details from toggling
                  handleCopy();
                }}
              >
                {copyButtonText}
              </button>
            )}
          </summary>
          <div 
            className="mt-4 prose max-w-none text-black max-h-96 overflow-y-auto"
            dangerouslySetInnerHTML={{ __html: analysisHtml }}
          />
          <div ref={analysisEndRef} />
        </details>
      </div>
    </div>
  );
};

export default PromptDisplay;
